services:
  - type: web
    name: whatsapp-cleaner
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
